name: GitHub Actions Build and Deploy 
on:   
  push:
    branches:
    - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - run: yarn install
      
    - run: yarn build

    - name: Vuepress deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        BUILD_DIR: docs/.vuepress/dist